name: Analyse

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Static analyse
        uses: docker://vimeo/psalm-github-actions
        with:
          php_version: 8.0
          version: 2
          security_analysis: true
          composer_require_dev: true
          composer_ignore_platform_reqs: true

      - name: Type check
        uses: make type-check