name: phpcs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: PHP Code Style (phpcs)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        run: |
          chmod +x ./scripts/codestyle.sh
          sh ./scripts/codestyle.sh master develop