name: phpcs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PHP Code Style (phpcs)
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/script.sh"
          sh "${GITHUB_WORKSPACE}/.github/scripts/codestyle.sh"