name: phpcs
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Composer install
        uses: php-actions/composer@v5
        with:
          php_version: 8.0
          version: 2
          dev: yes
          args: --profile --ignore-platform-reqs
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump SHA
        run: echo "$GITHUB_HEAD_REF"
      - name: PHP Code Style (phpcs)
        run: |
          ls ./vendor/
          chmod +x ./scripts/codestyle.sh
          sh ./scripts/codestyle.sh e1fca1305b083cc7f586624c0e449475e4a3a4ee eb85ad9f5aaffcb5ac1ab916e18980362205c526