name: phpcs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: PHP Code Style (phpcs)
        working-directory: ./../../
        run: |
          chmod +x "./scripts/codestyle.sh"
          sh "./scripts/codestyle.sh master develop"