name: Tests

on: [ push ]

jobs:
  build-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: make run-tests
        with:
          php_version: 8.0
          version: 2
          security_analysis: true
          composer_require_dev: true
          composer_ignore_platform_reqs: true
