name: Validate

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Validate dependencies
        uses: php-actions/composer@v5
        with:
          command: validate